### ISSUE TITLE
Doesn't work in Grails 2.2.x

### ISSUE THREAD

**Issue by martinschayna** [kenliu/grails-elastic-beanstalk#2]
groovy.lang.MissingPropertyException: No such property: warName for class: AwsEbDeploy

Maybe some incompatibility with default script _GrailsWar.groovy?

Stacktrace follows.

```
groovy.lang.MissingPropertyException: No such property: warName for class: AwsEbDeploy
    at AwsEbDeploy$_run_closure1.doCall(AwsEbDeploy:21)
    at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
    at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
    at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
    at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
    at gant.Gant.withBuildListeners(Gant.groovy:427)
    at gant.Gant.this$2$withBuildListeners(Gant.groovy)
    at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
    at gant.Gant.dispatch(Gant.groovy:415)
    at gant.Gant.this$2$dispatch(Gant.groovy)
    at gant.Gant.invokeMethod(Gant.groovy)
    at gant.Gant.executeTargets(Gant.groovy:591)
    at gant.Gant.executeTargets(Gant.groovy:590)
```

**Comment by kenliu** [comment]
Can you tell me which version of Grails you are using? I've tested on 2.2.4 and didn't come across this issue (but did  find a different issue in 2.2.4)

**Comment by martinschayna** [comment]
Sorry, this bug appears in 2.2.2 and 2.2.3

**Comment by kenliu** [comment]
Hi - I tracked it down to the "warName" global variable being removed from the _GrailsWar.groovy script in 2.2.

https://github.com/grails/grails-core/commit/e31359b638ef77183403c216fc0e65b9d2f2e75f#scripts/_GrailsWar.groovy

Will have a workaround for this in the next day or two. Strange that I wasn't able to duplicate the exact problem, though.

**Comment by janwillies** [comment]
any update or workaround on this? I am running into the same bug with 2.2.4

**Comment by kenliu** [comment]
sorry for the delay. I have a fix ready and will publish it some time tomorrow morning.

**Comment by kenliu** [comment]
pushed new version v0.1.1
