### ISSUE TITLE
Copying files to "${stagingDir}.ebextensions" breaks custom configuration

### ISSUE THREAD

**Issue by okal** [kenliu/grails-elastic-beanstalk#34]
I'm trying to use the config files provided at http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.cloudwatchlogs.html to enable CloudWatch automatically. How I've done that is by including the following snippet in BuildConfig

```
grails.war.resources = { stagingDirectory, args ->
    copy(file:".ebextensions/cwl-setup.config", tofile: "${stagingDirectory}/.ebextensions/cwl-setup.config")
    copy(file:".ebextensions/cwl-webrequest-metrics.config", tofile: "${stagingDirectory}/.ebextensions/cwl-webrequest-metrics.config")
    copy(file:".ebextensions/eb-logs.config", tofile: "${stagingDirectory}/.ebextensions/eb-logs.config")
}
```

I created a .ebextensions directory at the project root, that is then used to populate the resulting .ebextensions directory at the WAR root. I'm getting the following exception when I run grails war.

```
| Error Exception occurred trigger event [CreateWarStart]: Failed to create extensions directory at /home/ubuntu/workspaces/onlinesms/target/stage/.ebextensions (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.RuntimeException: Failed to create extensions directory at /home/ubuntu/workspaces/onlinesms/target/stage/.ebextensions
    at _Events$_run_closure1.doCall(_Events.groovy:15)
    at _GrailsEvents_groovy$_run_closure5.doCall(_GrailsEvents_groovy:59)
    at _GrailsEvents_groovy$_run_closure5.call(_GrailsEvents_groovy)
    at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
    at War$_run_closure4.doCall(War:308)
    at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
    at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
    at java_util_concurrent_Callable$call.call(Unknown Source)
    at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
    at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
    at org.codehaus.gant.GantMetaClass.processClosure(GantMetaClass.java:81)
    at org.codehaus.gant.GantMetaClass.processArgument(GantMetaClass.java:95)
    at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:128)
    at War$_run_closure1.doCall(War.groovy:38)
    at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
    at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
    at java_util_concurrent_Callable$call.call(Unknown Source)
    at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
    at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
    at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
    at java_util_concurrent_Callable$call.call(Unknown Source)
    at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
    at java_util_concurrent_Callable$call.call(Unknown Source)
    at gant.Gant.withBuildListeners(Gant.groovy:427)
    at gant.Gant.this$2$withBuildListeners(Gant.groovy)
    at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
    at gant.Gant.dispatch(Gant.groovy:415)
    at gant.Gant.this$2$dispatch(Gant.groovy)
    at gant.Gant.invokeMethod(Gant.groovy)
    at gant.Gant.executeTargets(Gant.groovy:591)
    at gant.Gant.executeTargets(Gant.groovy:590)
```

I've traced the problem to https://github.com/kenliu/grails-elastic-beanstalk/blob/master/scripts/_Events.groovy, but I don't understand why it's happening. The ultimate result of this is that the beanstalk environment is stripped of all our custom configuration. #25 seems like it was meant to address this issue, but it appears inactive.

**Comment by okal** [comment]
Interestingly, CloudWatch Logs works, in spite of the rest of the config breaking.

**Comment by okal** [comment]
Turns out it was just a mismatch between what we'd named our properties (`jvmProperties`, instead of `jvmOptions`. `systemProperties` instead of `environmentProperties`) and what the plugin expected to find. :frowning:
